mojevrijemeje(90,50);
pocistisve();
defaultstaza();
_root.ljevirub = new Array("7.3","280.6","491.3");
_root.desnirub = new Array("240.7","451.3","694.1");
_root.ljevix = Number(_root.ljevirub[0]) + _root.sirinaigraca / 2;
_root.desnix = Number(_root.desnirub[0]) - _root.sirinaigraca / 2;
_root.levela = 3;
_root.bar = 0;
_root.vrat = 0;
_root.itemz = new Array("x","x","x","x","x","x","x","o","o","o","o");
stop();
